name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: 8.0.332+9
          cache: 'maven'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Send report to Coveralls
      run: mvn clean test jacoco:report coveralls:report -Drepotoken=${{ secrets.COVERALLS_REPO_TOKEN }}
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    
